min_linePointCount: 60
relevantScans_cnt: 5
max_FailCount: 4
max_AngleDiffBetweenRows: 0.25
max_AngleDiff_recent2current: 0.08
RANSAC_threshold: 0.04
pointCloudRange_Xmin: 0.0
pointCloudRange_Xmax: 1.25
pointCloudRange_Ymin: -0.075
pointCloudRange_Ymax: 0.85
